# Generated by Django 3.2.7 on 2021-09-19 07:12

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('pubdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('design_score', models.IntegerField(default=0)),
                ('usability_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('average_design', models.FloatField(default=0)),
                ('average_usability', models.FloatField(default=0)),
                ('average_content', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
